USE `BD2401`;
-- Excluindo o BD
-- DROP DATABASE `BD2401`;
-- Criando o Schema do BD
CREATE SCHEMA `BD2401`;
-- Criando a tabela
CREATE TABLE `BD2401`.`NEW_TABLE`(
	`ID_MEMBER` INT NOT NULL AUTO_INCREMENT,
    `FIRST_NAME` VARCHAR(20) NOT NULL,
    `ACTIVE` BIT(1) NULL DEFAULT 1,
    `WHEN_ADDED` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `LAST_MODIFIED` TIMESTAMP NULL 
		DEFAULT CURRENT_TIMESTAMP 
			ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(`ID_MEMBER`)
);

-- INSERINDO DADOS NA TABELA
INSERT INTO `BD2401`.`NEW_TABLE` (`FIRST_NAME`)
VALUES('Mauricio R Gonzatto');

INSERT INTO `BD2401`.`NEW_TABLE` (`FIRST_NAME`, `ACTIVE`)
VALUES('Olivia Gonzatto', 0);

INSERT INTO `BD2401`.`NEW_TABLE` (`FIRST_NAME`, `ACTIVE`)
VALUES('Cecilia Gonzatto', 0);

-- EXIBINDO/CONSULTANDO DADOS
SELECT * FROM `BD2401`.`NEW_TABLE`;

